services:
  # Distributed file storage
  ipfs:
    image: ipfs/kubo:latest
    ports:
      # P2P TCP/QUIC transports
      - 4001:4001
      - 4001:4001/udp
      # RPC API
      - "127.0.0.1:5001:5001"
      - "[::1]:5001:5001"
      # Gateway
      - "127.0.0.1:5001:5001"
      - "[::1]:8080:8080"
    volumes:
      # Import and export files from IPFS
      - ipfs-staging:/export
      # Persistent IPFS files
      - ipfs-data:/data/ipfs
    container_name: nullchan-ipfs

volumes:
  ipfs-staging:
  ipfs-data:
